version: "3"

services:
  app:
    container_name: timetracking
    hostname: timetracking
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/fonte
      - gems:/gems
    stdin_open: true
    tty: true

volumes:
  gems: